---
title: "tweetCOVID"
author: "Suschevskiy Vsevolod"
date: "6/15/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# wget https://zenodo.org/record/4593524/files/TweetsCOV19_062020_122020.tsv.gz?download=1

# gzip -dk TweetsCOV19_062020_122020.tsv.gz?download=1
```


```{r}
library(tidyverse)
library(vroom)
library(stringr)
```

```{r}
tweets_df <-
  vroom::vroom("TweetsCOV19_062020_122020.tsv", 
               col_names = c("Tweet_Id", "Username" ,"Timestamp" ,"Followers", "Friends", "Retweets", "Favorites", "Entities" ,"Sentiment", "Mentions" ,"Hashtags","URLs"))

```

```{r}
?separate
?str_glue

tweets_df %>% 
  head(1000) %>% 
  mutate(Entities = strsplit(Entities, ";")) %>%
        unnest(Entities) %>%
        group_by(Tweet_Id) %>%
        mutate(row = paste("Entity_", row_number())) %>%
        spread(row, Entities)
```

```{r}
library(tidytext)

tweets_df %>% 
  select(Timestamp, Hashtags) %>%
  head(10000) %>% 
  filter(Hashtags != "null;") %>% 
  unnest_tokens(Hashtag, Hashtags,token = "words") -> tweets_hastags
```

```{r}
library(lubridate)
?parse_date_time

tweets_hastags %>% 
  head(100) %>% 
  mutate(Timestamp = Timestamp %>% 
           str_remove("... ") %>% 
           str_remove(" \\+.+")) %>%
  mutate(Timestamp = paste("2020 " ,Timestamp)) %>% 
  mutate(date = ymd_hms(Timestamp))
```

